In [1]:
import tensorflow as tf
from tensorflow.keras import layers
import pandas as pd
import numpy as np
from tensorflow.keras import datasets, layers, models
from tensorflow.keras.utils import to_categorical

In [2]:
import os
from google.colab import drive
drive.mount('/content/drive')
os.chdir('/content/drive/My Drive/Vandeir/Iris')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
df = pd.read_csv("Doen.csv")
df

doenca         sintoma1  ...           sintoma4                remedios
0        AVC  confusão mental  ...  alteração da fala  ácido acetilsalicílico
1      Gripe            Tosse  ...    Dor de garganta              Multigripe
2     Dengue            Febre  ...            Manchas                Dipirona
3  Pneumonia            Febre  ...              Tosse               Zanamivir
4     Colica            Enjoo  ...            Desmaio                Buscopan

[5 rows x 6 columns]

In [4]:
X = df.iloc[:,1:6].values
y = df.iloc[:,0].values

In [5]:
from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y_convertido = encoder.fit_transform(y)

In [6]:
y

array(['AVC', 'Gripe', 'Dengue', 'Pneumonia', 'Colica'], dtype=object)

In [7]:
y = pd.get_dummies(y_convertido).values

In [8]:
y

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0]], dtype=uint8)

In [9]:
sintoma1 = LabelEncoder()
X[:, 0] = sintoma1.fit_transform(X[:, 0])
X

array([[3, 'alteração na visão', 'fraqueza', 'alteração da fala',
        'ácido acetilsalicílico'],
       [2, 'Congestão nasal', 'Dor de cabeça', 'Dor de garganta',
        'Multigripe'],
       [1, 'Dor no corpo', 'Dor de cabeça', 'Manchas', 'Dipirona'],
       [1, 'Dor no peito', 'Falta de ar', 'Tosse', 'Zanamivir'],
       [0, 'Diarreia', 'Vomito', 'Desmaio', 'Buscopan']], dtype=object)

In [10]:
sintoma2 = LabelEncoder()
X[:, 1] = sintoma2.fit_transform(X[:, 1])
X

array([[3, 4, 'fraqueza', 'alteração da fala', 'ácido acetilsalicílico'],
       [2, 0, 'Dor de cabeça', 'Dor de garganta', 'Multigripe'],
       [1, 2, 'Dor de cabeça', 'Manchas', 'Dipirona'],
       [1, 3, 'Falta de ar', 'Tosse', 'Zanamivir'],
       [0, 1, 'Vomito', 'Desmaio', 'Buscopan']], dtype=object)

In [11]:
sintoma3 = LabelEncoder()
X[:, 2] = sintoma3.fit_transform(X[:, 2])
X

array([[3, 4, 3, 'alteração da fala', 'ácido acetilsalicílico'],
       [2, 0, 0, 'Dor de garganta', 'Multigripe'],
       [1, 2, 0, 'Manchas', 'Dipirona'],
       [1, 3, 1, 'Tosse', 'Zanamivir'],
       [0, 1, 2, 'Desmaio', 'Buscopan']], dtype=object)

In [12]:
sintoma4 = LabelEncoder()
X[:, 3] = sintoma4.fit_transform(X[:, 3])
X

array([[3, 4, 3, 4, 'ácido acetilsalicílico'],
       [2, 0, 0, 1, 'Multigripe'],
       [1, 2, 0, 2, 'Dipirona'],
       [1, 3, 1, 3, 'Zanamivir'],
       [0, 1, 2, 0, 'Buscopan']], dtype=object)

In [13]:
remedio = LabelEncoder()
X[:, 4] = remedio.fit_transform(X[:, 4])
X

array([[3, 4, 3, 4, 4],
       [2, 0, 0, 1, 2],
       [1, 2, 0, 2, 1],
       [1, 3, 1, 3, 3],
       [0, 1, 2, 0, 0]], dtype=object)

In [14]:
X

array([[3, 4, 3, 4, 4],
       [2, 0, 0, 1, 2],
       [1, 2, 0, 2, 1],
       [1, 3, 1, 3, 3],
       [0, 1, 2, 0, 0]], dtype=object)

In [15]:
X = np.asarray(X).astype('float32')

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [17]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(20, activation='gelu'),
    tf.keras.layers.Dense(15, activation='gelu'),
    tf.keras.layers.Dense(5, activation='sigmoid')
  ])
model

In [18]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [19]:
model.fit(X_train, y_train, batch_size=50, epochs=100)

Epoch 1/100
1/1 [==============================] - 1s 711ms/step - loss: 1.8843 - accuracy: 0.2500
Epoch 2/100
1/1 [==============================] - 0s 7ms/step - loss: 1.8517 - accuracy: 0.2500
Epoch 3/100
1/1 [==============================] - 0s 19ms/step - loss: 1.8205 - accuracy: 0.5000
Epoch 4/100
1/1 [==============================] - 0s 9ms/step - loss: 1.7905 - accuracy: 0.5000
Epoch 5/100
1/1 [==============================] - 0s 7ms/step - loss: 1.7617 - accuracy: 0.5000
Epoch 6/100
1/1 [==============================] - 0s 10ms/step - loss: 1.7341 - accuracy: 0.5000
Epoch 7/100
1/1 [==============================] - 0s 5ms/step - loss: 1.7077 - accuracy: 0.5000
Epoch 8/100
1/1 [==============================] - 0s 10ms/step - loss: 1.6823 - accuracy: 0.5000
Epoch 9/100
1/1 [==============================] - 0s 8ms/step - loss: 1.6580 - accuracy: 0.5000
Epoch 10/100
1/1 [==============================] - 0s 7ms/step - loss: 1.6346 - accuracy: 0.5000
Epoch 11/100
1/1 [======

In [20]:
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print('Resultado loss:', loss)
print('Resultado accuracy:', accuracy)

Resultado loss: 3.054095506668091
Resultado accuracy: 0.0


In [21]:
y_pred = model.predict(X_test[0:2])

In [22]:
y_pred

array([[0.70187724, 0.6382054 , 0.26017225, 0.4605706 , 0.68073773]],
      dtype=float32)

In [23]:
y_test[0:1]

array([[0, 0, 1, 0, 0]], dtype=uint8)